# Generated by Django 3.0.4 on 2020-03-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MegacademiaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sharingfileinfo',
            table='sharing_file_info',
        ),
    ]
